server:
  port: 8881
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/dbauth?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: rootroot
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        ddl-auto: validate
check-user-scopes: true
logging:
  level:
    org:
      hibernate:
        type: trace
#flyway:
#  url: jdbc:mysql://localhost:3306/dbauth?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#  schemas: dbauth
#  user: root
#  password: rootroot
