server:
  port: 8882
spring:
  application:
    name: product-service
  datasource:
    url : jdbc:mysql://localhost:3306/dbproduct?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: rootroot
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace